DROP TABLE IF EXISTS combo_group_item CASCADE;
DROP TABLE IF EXISTS combo_group_items CASCADE;
DROP TABLE IF EXISTS combo_group CASCADE;
DROP TABLE IF EXISTS combo_groups CASCADE;

DROP TABLE IF EXISTS menu_item_option_group CASCADE;
DROP TABLE IF EXISTS menu_item_option_groups CASCADE;
DROP TABLE IF EXISTS menu_item_option CASCADE;
DROP TABLE IF EXISTS menu_item_options CASCADE;

DROP TABLE IF EXISTS option_item CASCADE;
DROP TABLE IF EXISTS option_items CASCADE;
DROP TABLE IF EXISTS option_group CASCADE;
DROP TABLE IF EXISTS option_groups CASCADE;

DROP TABLE IF EXISTS menu_item_variant CASCADE;
DROP TABLE IF EXISTS menu_item_variants CASCADE;

DROP TABLE IF EXISTS menu_item CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;

DROP TABLE IF EXISTS topic CASCADE;
DROP TABLE IF EXISTS topics CASCADE;

DROP TABLE IF EXISTS restaurant_users CASCADE;
DROP TABLE IF EXISTS restaurant_hours CASCADE;
DROP TABLE IF EXISTS restaurant CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;

-- Drop enum types
DROP TYPE IF EXISTS menu_item_type CASCADE;