// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Restaurant struct {
	ID          int32
	Name        string
	Description *string
	Address     *string
	Category    *string
	City        *string
	District    *string
	LogoUrl     *string
	BannerUrl   *string
	PhoneNumber *string
	WebsiteUrl  *string
	Email       *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedBy   uuid.UUID
	UpdatedBy   uuid.UUID
	DeleteAt    time.Time
	Status      string
}

type RestaurantHour struct {
	RestaurantID int32
	DayOfWeek    int32
	OpenTime     string
	CloseTime    string
	IsClosed     bool
}

type RestaurantUser struct {
	ID           int32
	RestaurantID int32
	UserID       uuid.UUID
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeleteAt     time.Time
}
