// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Role struct {
	ID        int32
	RoleName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	FullName     string
	Email        *string
	PasswordHash string
	RoleID       int
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
