// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users" (email, full_name, password_hash, role_id) VALUES ($1, $2, $3,(SELECT id FROM "roles" WHERE role_name = 'user'))
RETURNING id
`

type CreateUserParams struct {
	Email        *string
	FullName     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.FullName, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.email, u.full_name, r.role_name, u.password_hash, u.is_active, u.created_at, u.updated_at FROM "users" u
LEFT JOIN  "roles" r ON r.id = u.role_id
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID
	Email        *string
	FullName     string
	RoleName     *string
	PasswordHash string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.RoleName,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.email, u.full_name, r.role_name, u.is_active, u.created_at, u.updated_at FROM "users" u
LEFT JOIN "roles" r ON r.id = u.role_id
WHERE u.id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID        uuid.UUID
	Email     *string
	FullName  string
	RoleName  *string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.RoleName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT u.id, u.email, u.full_name, r.role_name, u.is_active, u.created_at, u.updated_at FROM "users" u
LEFT JOIN  "roles" r ON r.id = u.role_id
WHERE full_name = $1 LIMIT 1
`

type GetUserByNameRow struct {
	ID        uuid.UUID
	Email     *string
	FullName  string
	RoleName  *string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByName(ctx context.Context, fullName string) (GetUserByNameRow, error) {
	row := q.db.QueryRow(ctx, getUserByName, fullName)
	var i GetUserByNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.RoleName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT  r.role_name FROM "users" u
LEFT JOIN  "roles" r ON r.id = u.role_id
WHERE u.id = $1 AND u.is_active = $2 LIMIT 1
`

type GetUserRoleParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (*string, error) {
	row := q.db.QueryRow(ctx, getUserRole, arg.ID, arg.IsActive)
	var role_name *string
	err := row.Scan(&role_name)
	return role_name, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "users"
SET full_name = $1, email = $2, password_hash = $3, is_active = $4, updated_at = NOW()
WHERE id = $5
RETURNING id, full_name, email, password_hash, role_id, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	FullName     string
	Email        *string
	PasswordHash string
	IsActive     bool
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.Email,
		arg.PasswordHash,
		arg.IsActive,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
