// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users" (email, full_name, password_hash, role_id)
VALUES (
    $1::TEXT,
    $2::TEXT,
    $3::TEXT,
    (SELECT id FROM "roles" WHERE role_name = 'user')
)
RETURNING id
`

type CreateUserParams struct {
	Email        string
	FullName     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.FullName, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPasswordByID = `-- name: GetPasswordByID :one
SELECT password_hash
FROM "users"
WHERE id = $1::UUID
`

func (q *Queries) GetPasswordByID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordByID, userID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.email, u.full_name, r.role_name, u.password_hash, u.is_active, u.created_at, u.updated_at, u.image_url
FROM "users" u
LEFT JOIN "roles" r ON r.id = u.role_id
WHERE u.email = $1::TEXT
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID
	Email        *string
	FullName     string
	RoleName     *string
	PasswordHash string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ImageUrl     *string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.RoleName,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.email, u.full_name, r.role_name, u.is_active, u.created_at, u.updated_at, u.image_url
FROM "users" u
LEFT JOIN "roles" r ON r.id = u.role_id
WHERE u.id = $1::UUID
LIMIT 1
`

type GetUserByIDRow struct {
	ID        uuid.UUID
	Email     *string
	FullName  string
	RoleName  *string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	ImageUrl  *string
}

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.RoleName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT r.role_name
FROM "users" u
LEFT JOIN "roles" r ON r.id = u.role_id
WHERE u.id = $1::UUID
  AND u.is_active = $2::BOOLEAN
LIMIT 1
`

type GetUserRoleParams struct {
	UserID   uuid.UUID
	IsActive bool
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (*string, error) {
	row := q.db.QueryRow(ctx, getUserRole, arg.UserID, arg.IsActive)
	var role_name *string
	err := row.Scan(&role_name)
	return role_name, err
}

const updatePasswordByID = `-- name: UpdatePasswordByID :exec
UPDATE "users"
SET password_hash = $1::TEXT
WHERE id = $2::UUID
`

type UpdatePasswordByIDParams struct {
	PasswordHash string
	UserID       uuid.UUID
}

func (q *Queries) UpdatePasswordByID(ctx context.Context, arg UpdatePasswordByIDParams) error {
	_, err := q.db.Exec(ctx, updatePasswordByID, arg.PasswordHash, arg.UserID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "users"
SET full_name = $1::TEXT,
    email = $2::TEXT,
    password_hash = $3::TEXT,
    image_url = $4::TEXT,
    is_active = $5::BOOLEAN,
    updated_at = NOW()
WHERE id = $6::UUID
`

type UpdateUserParams struct {
	FullName     string
	Email        string
	PasswordHash string
	ImageUrl     string
	IsActive     bool
	UserID       uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.FullName,
		arg.Email,
		arg.PasswordHash,
		arg.ImageUrl,
		arg.IsActive,
		arg.UserID,
	)
	return err
}
